eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    config:
      override-system-properties: false # Disable overriding of system properties

management:
  tracing:
    sampling:
      probability: 1.0 # Set to 1.0 for full tracing, adjust as needed