spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/albaridbank
    username: albaridbank
    password: 123456
    driver-class-name: org.postgresql.Driver
    #authentication-database: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  flyway: # is to manage the database schema in a structured and organized way
      baseline-on-migrate: true
      enabled: true
      baseline-description: "Baseline for the database"
      baseline-version: 0
      user: ${spring.datasource.username}
      password: ${spring.datasource.password}

# Configuration SpringDoc/Swagger
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    enabled: true

# Configuration de log
logging:
  level:
    com.albaridbank: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

# Configuration pour les clients Feign
customer-service:
  url: http://localhost:8091/api/customer

server:
  port: 8092

# For Swagger UI: http://localhost:8092/swagger-ui.html
# For the raw OpenAPI Specification: http://localhost:8092/api-docs
