spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/albaridbank
    username: albaridbank
    password: 123456
    driver-class-name: org.postgresql.Driver
    authentication-database: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  flyway: # is to manage the database schema in a structured and organized way
    baseline-on-migrate: true
    enabled: true
    baseline-description: "Baseline for the database"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration

# Configuration SpringDoc/Swagger
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    enabled: true

# Configuration pour la génération de rapports
report:
  storage:
    location: ${user.home}/albaridbank-reports
    max-age-days: 30  # Durée de conservation des rapports en jours

# Configuration de log
logging:
  level:
    com.albaridbank: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG

# Configuration pour les clients Feign
customer-service:
  url: http://localhost:8091/api/customer

server:
  port: 8091
  servlet:
    context-path: /api/edition
