spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Enable service discovery for routing
      routes:
        # Customer Service Route
        - id: customer-service
          uri: lb:http://CUSTOMER-SERVICE # Load balancer URI for customer service using service discovery
          predicates:
            - Path=/api/v1/client/** # Route for customer service
        - id: customer-service
          uri: lb:http://CUSTOMER-SERVICE # Load balancer URI for customer service using service discovery
          predicates:
            - Path=/api/v1/compte/** # Route for account service
        # Branche Service Route
        - id: branche-service
          uri: lb:http://BRANCHE-SERVICE # Load balancer URI for branche service using service discovery
          predicates:
            - Path=/api/v1/branches/** # Route for branche service
        # Edition Service Route
        - id: edition-service
          uri: lb:http://EDITION-SERVICE # Load balancer URI for edition service
          predicates:
            - Path=/api/v1/rapportccp/** # Route for edition service
server:
  port: 8222 # Port to run the gateway service