spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/client/**,/api/v1/compte/**
        - id: branche-service
          uri: lb://branche-service
          predicates:
            - Path=/api/v1/branches/**
        - id: edition-service
          uri: lb://edition-service
          predicates:
            - Path=/api/v1/export/excel/**

server:
  port: 8222