-- Table SGC_REF_AGENCE
CREATE TABLE sgc_ref_agence (
    codburpo VARCHAR(6) NOT NULL,
    codreg INTEGER,
    libreg VARCHAR(200),
    typbur VARCHAR(10),
    chaindsn VARCHAR(20),
    ip VARCHAR(20) NOT NULL,
    src_cre VARCHAR(4),
    pole VARCHAR(2),
    codezone VARCHAR(3),
    libelle_zone VARCHAR(50),
    codegroupe VARCHAR(6),
    libelle_groupe VARCHAR(50),
    codelocalite VARCHAR(3),
    libelle_localite VARCHAR(50),
    categorie VARCHAR(3),
    responsable VARCHAR(200),
    remontee CHAR(1),
    statut CHAR(1),
    codburpo_ra VARCHAR(6),
    observation VARCHAR(100),
    typeconnexion VARCHAR(5),
    codelocbkam VARCHAR(4),
    liblocbkam VARCHAR(50),
    codregbkam VARCHAR(2),
    libregbkam VARCHAR(50),
    adresse VARCHAR(200),
    codburbkam VARCHAR(5),
    codesrbm VARCHAR(2),
    codebkam VARCHAR(4),
    ips VARCHAR(10),
    sig VARCHAR(10),
    codepostale VARCHAR(10),
    telephone_fixe VARCHAR(15),
    telephone_mobile VARCHAR(15),
    catagence VARCHAR(10),
    codburpo_wu VARCHAR(10),
    libelle_burpo VARCHAR(200),
    code_pole INTEGER,
    deploye CHAR(1),
    datedeploiement DATE,
    adeployer CHAR(1),
    matriculereceveur VARCHAR(10),
    typeagence INTEGER,
    faxe VARCHAR(20),
    email VARCHAR(20),
    PRIMARY KEY(codburpo)
);

-- Table UTILISATEURS
CREATE TABLE utilisateurs (
    id_utilisateur SERIAL NOT NULL,
    coderole SMALLINT,
    codeutilisateur VARCHAR(20),
    codeetablissement VARCHAR(6),
    nomutilisateur VARCHAR(50),
    prenomutilisateur VARCHAR(50),
    motpasse VARCHAR(50),
    matricule VARCHAR(50),
    datedebut DATE,
    datefin DATE,
    etat SMALLINT,
    prm_connexion SMALLINT,
    date_dernier_maj_mpd DATE,
    utilisateur_maj VARCHAR(20),
    date_creation DATE,
    date_maj DATE,
    PRIMARY KEY(id_utilisateur),
    FOREIGN KEY(codeetablissement) REFERENCES sgc_ref_agence(codburpo)
);

-- Table CATE_SOCIO_PROF
CREATE TABLE cate_socio_prof (
    codsocpr NUMERIC(3) NOT NULL,
    libsocpr VARCHAR(200) NOT NULL,
    cofacasp NUMERIC(2) NOT NULL,
    datdebeff DATE NOT NULL,
    datfineff DATE,
    PRIMARY KEY(codsocpr)
);

-- Table SITUATION_JURIDIQU
CREATE TABLE situation_juridiqu (
    codsitju NUMERIC(2) NOT NULL,
    libesitu VARCHAR(32),
    datdebeff DATE,
    datfineff DATE,
    PRIMARY KEY(codsitju)
);

-- Table CLIENT
CREATE TABLE client (
    idenclie NUMERIC(10) NOT NULL,
    cateclie NUMERIC(2) NOT NULL,
    typeclie VARCHAR(5),
    nomrais VARCHAR(120) NOT NULL,
    prenclie VARCHAR(20),
    civiclie VARCHAR(5),
    nume_telb VARCHAR(15),
    nume_teld VARCHAR(15),
    nume_gsm VARCHAR(15),
    nume_fax VARCHAR(15),
    datenais DATE,
    lieunais VARCHAR(30),
    sexeclie VARCHAR(2),
    typepiec VARCHAR(1),
    numpieid VARCHAR(15),
    datpieid DATE,
    revemens NUMERIC(15,2),
    situfami NUMERIC(2),
    situjuri NUMERIC(2),
    codsocpr NUMERIC(3),
    sectacti VARCHAR(5),
    ageneco VARCHAR(5),
    codforju NUMERIC(2),
    statclie NUMERIC(1),
    numregco VARCHAR(20),
    adremail VARCHAR(60),
    numepate VARCHAR(11),
    numevisa VARCHAR(11),
    capisoci NUMERIC(14),
    nombempl INTEGER,
    centrc VARCHAR(4),
    titre VARCHAR(2),
    domisala VARCHAR(1),
    misecont VARCHAR(1),
    segment INTEGER,
    cotarisq VARCHAR(8),
    datecrea DATE,
    datogmaj DATE,
    proplog VARCHAR(1),
    idenbam VARCHAR(12),
    numcenrs VARCHAR(15),
    agegescl NUMERIC(5,0),
    usegescl VARCHAR(7),
    codetati NUMERIC(4),
    codpayrs VARCHAR(2),
    codenate VARCHAR(2),
    donneerro VARCHAR(1),
    cliefiab SMALLINT NOT NULL,
    cliepros SMALLINT NOT NULL,
    nompere VARCHAR(50),
    nommere VARCHAR(50),
    precture INTEGER,
    patente VARCHAR(50),
    codpaysnaiss VARCHAR(2),
    codpayspass VARCHAR(2),
    adressemailnov VARCHAR(120),
    code_fdc_user INTEGER,
    code_info_clt INTEGER,
    PRIMARY KEY(idenclie),
    FOREIGN KEY(codsocpr) REFERENCES cate_socio_prof(codsocpr),
    FOREIGN KEY(situjuri) REFERENCES situation_juridiqu(codsitju)
);

-- Table COMPTE
CREATE TABLE compte (
    codcatcp NUMERIC(3) NOT NULL,
    codscatcp NUMERIC(2) NOT NULL,
    idencomp NUMERIC(12) NOT NULL,
    idenclie NUMERIC(10) NOT NULL,
    inticomp VARCHAR(120) NOT NULL,
    dateouve DATE NOT NULL,
    dateclot DATE,
    datogmaj DATE,
    bloqadr CHAR(1),
    datetacp DATE,
    n_sig INTEGER,
    codeinst NUMERIC(1),
    codclaure NUMERIC(2),
    codetacp VARCHAR(1) NOT NULL,
    cle_comp SMALLINT,
    codebpcpt NUMERIC(5,0) NOT NULL,
    dateremb DATE,
    cmptmand CHAR(1),
    cptedeco CHAR(1),
    codbpini NUMERIC(5,0),
    usrgestcp VARCHAR(7) NOT NULL,
    comoetco NUMERIC(3,0),
    codepinn NUMERIC(4),
    comptmon CHAR(1),
    nserliv NUMERIC(7),
    typerela VARCHAR(2),
    perirele VARCHAR(2),
    codedevi VARCHAR(4),
    PRIMARY KEY(idencomp),
    FOREIGN KEY(idenclie) REFERENCES client(idenclie),
    FOREIGN KEY(codebpcpt) REFERENCES sgc_ref_agence(codburpo)
);

-- Table ADRESSE_LINK
CREATE TABLE adresse_link (
    numeiden SERIAL NOT NULL,
    idenclie NUMERIC(10) NOT NULL,
    idencomp NUMERIC(12),
    codtypad VARCHAR(2) NOT NULL,
    codcatad VARCHAR(2) NOT NULL,
    intitule1 VARCHAR(120),
    intitule2 VARCHAR(60),
    intitule3 VARCHAR(60),
    intitule4 VARCHAR(60),
    codepays VARCHAR(2),
    codevill INTEGER,
    codepost VARCHAR(5),
    codburpo NUMERIC(5,0),
    datogmaj DATE,
    codburog NUMERIC(5,0),
    numordog NUMERIC(6,0),
    libeville VARCHAR(100),
    PRIMARY KEY(numeiden),
    FOREIGN KEY(idenclie) REFERENCES client(idenclie),
    FOREIGN KEY(idencomp) REFERENCES compte(idencomp)
);

-- Table CTR_PACK
CREATE TABLE ctr_pack (
    codepack NUMERIC(5) NOT NULL,
    codeperi VARCHAR(2),
    libepack VARCHAR(80) NOT NULL,
    datdebeff DATE NOT NULL,
    datfineff DATE,
    montant NUMERIC(15,5),
    codtypop NUMERIC(15,5),
    codpackrempl NUMERIC(15,5),
    cond_general VARCHAR(255),
    localis_exige VARCHAR(1),
    url_clause_juridique VARCHAR(255),
    url_entete VARCHAR(255),
    url_resiliation VARCHAR(255),
    statut_deploiement INTEGER DEFAULT NULL,
    prelevement_differe INTEGER,
    conventionne VARCHAR(1),
    ordre INTEGER,
    est_conv_obligatoire BOOLEAN,
    nat_migration NUMERIC(16),
    PRIMARY KEY(codepack)
);

-- Table CTR_PRODUIT
CREATE TABLE ctr_produit (
    codeprod NUMERIC(5) NOT NULL,
    libeprod VARCHAR(200),
    com_com NUMERIC(2),
    datdebeff TIMESTAMP,
    datfineff TIMESTAMP,
    commercialiseon VARCHAR(1),
    idfamprod INTEGER,
    unicite_acces VARCHAR(1),
    redirection_obli VARCHAR(1),
    url_sousc VARCHAR(255),
    rattach CHAR(1),
    tarif NUMERIC(15,5),
    localis_exige VARCHAR(1),
    ordre INTEGER,
    statut_deploiement INTEGER,
    codprodrempl NUMERIC(5),
    nat_migration NUMERIC(16),
    PRIMARY KEY(codeprod)
);

-- Table CTR_CONTRAT
CREATE TABLE ctr_contrat (
    idcontrat SERIAL NOT NULL,
    numcontrat VARCHAR(20),
    idenclie NUMERIC(10) NOT NULL,
    idencomp NUMERIC(12) NOT NULL,
    codtypcontrat NUMERIC(5),
    codeprod NUMERIC(5),
    sousc_statut VARCHAR(2),
    codmotif NUMERIC(5),
    codepack NUMERIC(5),
    codtyptarif NUMERIC(5),
    usersaisi NUMERIC(7),
    numordog NUMERIC(6),
    usermaj NUMERIC(7),
    datemaj TIMESTAMP,
    userres NUMERIC(7),
    codburpores NUMERIC(5),
    codburpomaj NUMERIC(5),
    codburposai NUMERIC(5),
    dateres TIMESTAMP,
    date_premier_prel TIMESTAMP,
    sousc_date TIMESTAMP,
    date_proch_prel DATE,
    montant_res NUMERIC(20),
    echeance_res NUMERIC(5),
    datedernierprelv TIMESTAMP,
    ref_externe VARCHAR(25),
    contrat_attach INTEGER,
    montant NUMERIC(15,5),
    codeconv NUMERIC(15,5),
    dt_basculement TIMESTAMP,
    idoldpack NUMERIC(5),
    idoldconv NUMERIC(5),
    dt_modifconv TIMESTAMP,
    canal_sousc INTEGER,
    canal_resil INTEGER,
    PRIMARY KEY(idcontrat),
    FOREIGN KEY(idenclie) REFERENCES client(idenclie),
    FOREIGN KEY(idencomp) REFERENCES compte(idencomp),
    FOREIGN KEY(codeprod) REFERENCES ctr_produit(codeprod),
    FOREIGN KEY(codepack) REFERENCES ctr_pack(codepack)
);

-- Table CTR_SOUSCRIPTION_PACK
CREATE TABLE ctr_souscription_pack (
    idsoupackprod SERIAL NOT NULL,
    idencomp NUMERIC(12) NOT NULL,
    idcontrat INTEGER,
    codeprod NUMERIC(5),
    idenclie NUMERIC(10) NOT NULL,
    statut VARCHAR(1),
    date_statut TIMESTAMP,
    montant NUMERIC(20),
    usersaisi NUMERIC(7),
    codburposai NUMERIC(5),
    date_saisi TIMESTAMP,
    numordog NUMERIC(6),
    usermaj NUMERIC(7),
    codburpomaj NUMERIC(5),
    datemaj DATE,
    userres NUMERIC(7),
    codburpores NUMERIC(5),
    dateres DATE,
    date_premier_prel DATE,
    date_proch_prel DATE,
    identifiant_extern VARCHAR(40),
    PRIMARY KEY(idsoupackprod),
    FOREIGN KEY(idencomp) REFERENCES compte(idencomp),
    FOREIGN KEY(idenclie) REFERENCES client(idenclie),
    FOREIGN KEY(idcontrat) REFERENCES ctr_contrat(idcontrat),
    FOREIGN KEY(codeprod) REFERENCES ctr_produit(codeprod),
    FOREIGN KEY(codburposai) REFERENCES sgc_ref_agence(codburpo),
    FOREIGN KEY(codburpomaj) REFERENCES sgc_ref_agence(codburpo),
    FOREIGN KEY(codburpores) REFERENCES sgc_ref_agence(codburpo)
);